name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # Temporarily disable Black formatting check
    # - name: Check formatting with black
    #   run: |
    #     black --check .
    - name: Test with pytest
      env:
        API_KEY: demo
        AI_KEY: demo
      run: |
        cd $GITHUB_WORKSPACE && python -m pytest